image: openjdk:10-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/
      - kieker-bridge-raritan/build
      - kieker-bridge-raritan/raritan-simulator/build


test:
  stage: test
  tags:
    - dockerex
  script: ./gradlew check

deploy-raritan-bridge:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t titan-ccp-kieker-bridge-raritan ./kieker-bridge-raritan
    - docker tag titan-ccp-kieker-bridge-raritan industrialdevops/titan-ccp-kieker-bridge-raritan:latest
    - docker tag titan-ccp-kieker-bridge-raritan industrialdevops/titan-ccp-kieker-bridge-raritan:$(date +%Y%m%d%H%M%S)
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push industrialdevops/titan-ccp-kieker-bridge-raritan
    - docker logout
  only:
    - master


deploy-raritan-simulator:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t titan-ccp-raritan-simulator ./kieker-bridge-raritan/raritan-simulator
    - docker tag titan-ccp-raritan-simulator industrialdevops/titan-ccp-raritan-simulator:latest
    - docker tag titan-ccp-raritan-simulator industrialdevops/titan-ccp-raritan-simulator:$(date +%Y%m%d%H%M%S)
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push industrialdevops/titan-ccp-raritan-simulator
    - docker logout
  only:
    - master

deploy-load-tester-bridge:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t titan-ccp-load-tester-bridge ./load-tester-bridge
    - docker tag titan-ccp-load-tester-bridge industrialdevops/titan-ccp-load-tester-bridge:latest
    - docker tag titan-ccp-load-tester-bridge industrialdevops/titan-ccp-load-tester-bridge:$(date +%Y%m%d%H%M%S)
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push industrialdevops/titan-ccp-load-tester-bridge
    - docker logout
  only:
    - master