image: openjdk:10-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - kieker-bridge-raritan/build
      - kieker-bridge-raritan/raritan-simulator/build
      - .gradle


test:
  stage: test
  tags:
    - dockerex
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - kieker-bridge-raritan/build
      - kieker-bridge-raritan/raritan-simulator/build
      - .gradle

deploy:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull -t titan-ccp-kieker-bridge-raritan ./kieker-bridge-raritan
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - kieker-bridge-raritan/build
      - kieker-bridge-raritan/raritan-simulator/build
      - .gradle
